import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "./components/Navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Namka - Arch Digest",
  description: "Generated by Mahim Jain",
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-stone-50" suppressHydrationWarning>
        <div className="lg:grid lg:grid-cols-[200px_1fr]">
          <Navbar />
          <main className="pb-24 lg:pb-0">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}