import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Navbar from "./components/Navbar"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Namka - Arch Digest",
  description: "Generated by Mahim Jain",
  icons: {
  icon: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><rect width='100' height='100' rx='12' fill='%2344403c'/><text x='50' y='72' font-family='Arial,sans-serif' font-size='62' font-weight='bold' fill='%23f5f0eb' text-anchor='middle'>(N)</text></svg>",
},
}

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-stone-50" suppressHydrationWarning>
        <div className="lg:block">
          <Navbar />
          <main className="pb-24 lg:pb-0 lg:pl-[200px]">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
